# Generated by Django 5.2.5 on 2025-09-03 17:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding_choice', models.CharField(choices=[('coding', 'coding'), ('no-code', 'no-code')], max_length=10)),
                ('monthly_users', models.IntegerField(help_text='Estimate monthly active users')),
                ('runtime', models.CharField(choices=[('static', 'static'), ('serverless', 'serverless'), ('container', 'container')], max_length=20)),
                ('media_upload', models.BooleanField(default=False)),
                ('auth_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('techstack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='myapp.techstack')),
            ],
        ),
    ]
