# Generated by Django 5.2.5 on 2025-09-03 17:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('why', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_suggestions', to='myapp.deploymentpreference')),
            ],
        ),
    ]
