# Generated by Django 5.2.5 on 2026-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hostingsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
