# Generated by Django 5.2.5 on 2026-03-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_deploymentplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeploymentPlan',
        ),
    ]
